spring.application.name=pau-pevau

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/esquema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
